### ISSUE TITLE
10.1 support

### ISSUE THREAD

**Issue by meladroit** [phase/oot3dhax_installer#1]
So 10.1 payloads are out. Looking at the strings in the newest installer.3dsx, I would say the relevant part of the filename is
- 20480 for EUR and JPN
- 21504_usa for USA

but you should probably have someone else test these out for EUR and USA. I know N3DS_J_20480_9221.bin works for JPN 10.1 NEW.

**Comment by meladroit** [comment]
You can probably close this whenever pull request #2 makes it into the binaries.

**Comment by phase** [comment]
The latest release _should_ work, but I haven't tested it for 10.1.
