### ISSUE TITLE
Fails to download payload from server.

### ISSUE THREAD

**Issue by rdvl97** [phase/oot3dhax_installer#3]
When attempting to install, it will say that it failed to retrieve the payload from the download server.

**Comment by rdvl97** [comment]
is there a way to make it just use the payload file from the sd card?

**Comment by phase** [comment]
OoT3D doesn't have SD card access, so it can't load it from the SD card. Are you connected to the internet?

**Comment by rdvl97** [comment]
Yes, i have confirmed that I am connected to the internet.
im trying to download the payload for o3ds 10.1 and it returns the error
FFFFFFFE

This isnt the first time something like this has happened.  The current
homemenuhax installer suffers the same issue.
Is it possible for me to inject the payload manually via svdt?

**Comment by phase** [comment]
That is weird, can you send a screenshot of the error? I don't believe you can install payloads through svdt, but I've never used it before. I would try Tubehax.

**Comment by rdvl97** [comment]
oddly enough, attempting to take a screenshot causes your app to crash.  so i used my phone instead :P  sorry for potato quality...
top: http://i.imgur.com/RdafW7N.jpg
bottom: http://i.imgur.com/zhrmZP4.jpg  

Anyway, tubehax was patched by nintendo a couple weeks ago.

**Comment by xadox-1st** [comment]
Payload.bin and and save00.bin can be trafered to OoT3D CTR also with svdt.
I have done so.

Since I also get the error message FFFFFFFE I hat to search for a manually way to tranfer the files to CTR.

**Comment by meladroit** [comment]
See pull request #4. The installer needs to be updated—the 2.1 payloads are no longer available, and we need to move to fetching 2.5 payloads from a different URL.

The 2.5 payloads are also larger by a few KB, so you absolutely need to wipe save data before installing.

**Comment by artman41** [comment]
Error Code: FFFFFFFE

---

(What's shown on the top screen)

Selected firmware: OLD 3DS 9-9-0 EUR

Retrieving payload... POST5_E_19456_9221
Looks like something went wrong. :(

---

Using the files from Pull Request #5

**Comment by rdvl97** [comment]
@meladroit does that mean that we cant have any save files at all on there?

**Comment by phase** [comment]
@rdvl97 Yes, no save files other than the hax.

**Comment by rdvl97** [comment]
damn :/

**Comment by meladroit** [comment]
I'm also seeing the same error—I'm not sure why, but something probably went wrong in the recompilation. Let me try some stuff here ...

Actually, I'm now seeing it freeze up at 'Searching through local payloads ...' for some reason. Weird.

**Comment by phase** [comment]
Oh darn, I forgot the local payload code is still in there. We need to remove that and then build for the new payloads.

**Comment by meladroit** [comment]
Well, the 'checking through local payloads' part was broken (I assume it ended up making some sort of bad memory access). Rather than looping through stored payload names, you may want to make it just look for the exact payload you would want.

In the meantime, I've disabled the local payload loop for now, and downloading the payload works for me on my local branch (O3DS 10.0.0-U). Let me throw another pull request at the wall and see if it sticks.

**Comment by artman41** [comment]
![scr_1_top_left](https://cloud.githubusercontent.com/assets/5568965/10866985/066ce3cc-8043-11e5-8785-0c4afd80a23b.png)
![scr_1_bottom](https://cloud.githubusercontent.com/assets/5568965/10866986/066da3e8-8043-11e5-82e4-c5ccac0de9ac.png)

## now works:

Selected firmware: OLD 3DS 9-9-0 EUR

Retrieving payload... POST5_E_19456_9221
Searching through local payloads...

---

Current status:
  Successfully wrote to file!_19456_920000A478

---

Also, an FYI, when it prints in the top screen that is has installed oot3dhax, it doesn't clear the screen beforehand, meaning that the text merges with the "might lose data if you don't." text

**Comment by phase** [comment]
Thanks for testing! I'll look at why it isn't reseting the top screen.

**Comment by artman41** [comment]
Oh! Wait!

I tried to run the hax and it crashed my OOT,

"An error has occurred, forcing the software to close."

"The system will now restart."

**Comment by artman41** [comment]
want me to open another issue?

**Comment by phase** [comment]
@artman41 Yes please!
